### ISSUE TITLE
problems with client.get_banner_details

### ISSUE THREAD

**Issue by vincenthau07** [seriaati/genshin.py#100]
Items return are 3 in total, should be 4

**Comment by ashleney** [comment]
Cannot reproduce. Maybe an issue with some banner ids being cached by genshin itself? Would you mind providing a reproducible example?

**Comment by vincenthau07** [comment]
**code:**
import genshin, asyncio

client = genshin.Client()

banners = asyncio.run(client.get_banner_details())
for banner in banners:
    print(banner.banner_id)
print()
banner_ids = asyncio.run(client.get_banner_ids())
print(*banner_ids,sep="\n")

**output:**
68aabc0972fee6ab6abd45251bc85907e5f062cb
6bb70a968c3ff75e0ead26ae707aa3c726053aa2
f0d7ba12f99d3dcc19d498f30a98344acfb64334

f0d7ba12f99d3dcc19d498f30a98344acfb64334
6bb70a968c3ff75e0ead26ae707aa3c726053aa2
09e74f2553a19424132fa8a46d8dac707dbb7175
835dfda1ea8dfd16cff06d7b890f33210cb3e08e

**Comment by vincenthau07** [comment]
### code
```
import genshin, asyncio

client = genshin.Client()

banners = asyncio.run(client.get_banner_details())
for banner in banners:
    print(banner.banner_id)
print()
banner_ids = asyncio.run(client.get_banner_ids())
print(*banner_ids,sep="\n")
```
![image](https://user-images.githubusercontent.com/79790008/216297044-81d4af1c-d23c-4de2-9b28-eea84e307aa7.png)

**Comment by ashleney** [comment]
Oh gosh, I think it might be a good idea to just phase out locally stored banner ids.
