### ISSUE TITLE
get_genshin_characters return traveler's element as Anemo regardless of real element in-game

### ISSUE THREAD

**Issue by seriaati** [seriaati/genshin.py#102]
![image](https://user-images.githubusercontent.com/61446626/216990257-e836a649-7c95-498f-95fa-d1cac7f38c01.png)

The endpoint does return the correct element but the wrapper does not.

**Comment by ashleney** [comment]
I have no idea anymore. This is a reoccurring issue and it never works properly. If someone manages to fix this persistent bug I'd appreciate it but I genuinely do not know what to do.

**Comment by seriaati** [comment]
In line 62, you attempt to replace the character's element from the one that's in DB:
https://github.com/thesadru/genshin.py/blob/0985b854841a80b53ddffc00eb9e48c8583a3e00/genshin/models/genshin/character.py#L62

I'm assuming that the traveler's element is somehow hard coded to Anemo inside the DB, so no matter what element is returned from the response it will get replaced by Anemo.

I removed the element replacement and it returns the correct element for traveler.

**Comment by ashleney** [comment]
Yeah, I am aware of that. It's just that I need to somehow make it work for all possible API responses, considering how inconsistent they are. There always turns out to be one case where it doesn't work.

**Comment by seriaati** [comment]
I guess you just have to make a special case for traveler.
