### ISSUE TITLE
[Question] Compatibility with v2 cookie_token (redeem_code)

### ISSUE THREAD

**Issue by scmanjarrez** [seriaati/genshin.py#108]
Hi, is it possible to redeem gift codes using latest v2 cookies? I'm trying to use cookie_token_v2 with `redeem_code`, but I haven't had any luck.

**Comment by ashleney** [comment]
isn't redeem code only in-game for cn users? I don't think the hoyolab API supports that.

**Comment by scmanjarrez** [comment]
Mmmm, I was referring to gift.hoyoverse.com. I used to redeem code using you library with cookie_token (v1). In fact, I'm able to redeem codes with an old account still using v1 cookie_token

**Comment by ashleney** [comment]
Oh but I thought cookie_token_v2 is only for cn users though? I'll look into it but this seems very odd.

**Comment by scmanjarrez** [comment]
Mmm, that's weird. I'm using an EU account but my cookies all look like _v2.

**Comment by ashleney** [comment]
Yeah nvm, you're right. I think I confused it with something then.

**Comment by ashleney** [comment]
I think I understand the issue know, I'll attempt to fix it.

**Comment by scmanjarrez** [comment]
These are the cookies found in the request header of https://api-account-os.hoyoverse.com/account/binding/api/getUserGameRolesByCookieToken?lang=en&region=os_euro&game_biz=hk4e_global&sLangKey=en-us

```
_MHYUUID=xxxxxx; DEVICEFP_SEED_ID=xxxxxx; DEVICEFP_SEED_TIME=xxxxxxxc; DEVICEFP=xxxxx; mi18nLang=es-es; HYV_LOGIN_PLATFORM_TRACKING_MAP={}; HYV_LOGIN_PLATFORM_OPTIONAL_AGREEMENT={"content":[]}; cookie_token_v2=v2_xxxxx; account_mid_v2=xxxxx_hy; account_id_v2=xxxxxx
```
I can give you my v2 cookies and v1 cookies if needed

**Comment by ashleney** [comment]
Yeah, the issue is just an arbitrary check in the library, not anything with the API itself.
