### ISSUE TITLE
Allow for CN challenge to be used for sign-in

### ISSUE THREAD

**Issue by ashleney** [seriaati/genshin.py#116]
the CN sign-in implementation has many issues. Getting timed out or being forced to solve a geetest challenge is a common occurrence and genshin.py does not handle this.

See example patches: https://github.com/PaiGramTeam/PaiGram/blob/main/utils/patch/genshin.py

**Comment by luoshuijs** [comment]
If there are other CN developers who use this framework and plan to temporarily solve the challenge, I would recommend inheriting from `genshin.Client()` and overriding the method. I do not advise substituting some methods of an object with the methods of another object. The advantage of the former approach is that the editor won't recognize all sorts of strange errors, and it's more in line with object-oriented programming principles.
