### ISSUE TITLE
New characters without defined names return the wrong image url

### ISSUE THREAD

**Issue by grasssand** [seriaati/genshin.py#12]
Try to get the data with `get_partial_user`, the image url of `Yun Jin` will be like `https://upload-os-bbs.mihoyo.com/game_record/genshin/character_icon/UI_AvatarIcon_Yun Jin.png`, but the raw date is `UI_AvatarIcon_Yunjin.png`.

If you change the default language parameter when querying, , this problem will happen for all new characters because of the different language names.

I think the image url should be generated from the raw data instead of the character.name.

**Comment by ashleney** [comment]
This is a bug caused by an inconsistency in the API. Partial user data has the icon in the `image` field for some reason.
