### ISSUE TITLE
cookie_token no longer present in cookies

### ISSUE THREAD

**Issue by caemputer** [seriaati/genshin.py#120]
Seems like they've updated the cookies on both hoyoverse.com and hoyolab.com to not include the `cookie_token` anymore, thus breaking code claiming. The cookie from hoyolab.com now looks like this:
`G_ENABLED_IDPS=google; ltoken=xxx; ltuid=xxx; mi18nLang=en-us; DEVICEFP_SEED_ID=xxx; DEVICEFP_SEED_TIME=xxx; _MHYUUID=xxx; DEVICEFP=xxx`

**Comment by Polygonalr** [comment]
Just got hit with this problem when my old `cookie_tokens` no longer work. It seems like HoYoverse is in the midst of rolling out a new cookie system with the HttpOnly flag for `cookie_token_v2` set to true (and thus not being able to be grabbed with JavaScript 😕).

![image](https://github.com/thesadru/genshin.py/assets/16399656/3d6f4a89-cdb5-40c8-aa5c-b870b7ec5888)

Grabbing cookies for code claiming with the library just got more tedious, and the wrapper for code claiming has to be updated to accommodate for the new API.

**Comment by ashleney** [comment]
I'm pretty sure the library already supports `cookie_token_v2` and also getting http-only cookies from the browser. What specifically is failing?

We already had this issue with cn cookies.

**Comment by caemputer** [comment]
Ah that was a misunderstanding on my side then, my bad. If the library already supports the new token there is no issue. Thanks for clarifying.
