### ISSUE TITLE
Claim daily reward 

### ISSUE THREAD

**Issue by ar1ls** [seriaati/genshin.py#131]
collecting daily rewards does not work 2-4 days after its daily collection, because a captcha appears on hoyloab

**Comment by seriaati** [comment]
Well the library certainly can't magically solve the captcha for you.
You can buy a captcha solver and solve it by passing in the solved captcha as headers using `claim_daily_reward()`

**Comment by GauravM512** [comment]
> collecting daily rewards does not work 2-4 days after its daily collection, because a captcha appears on hoyloab

What do you expect here?

**Comment by lucyfyy** [comment]
is it this error? "Geetest triggered during daily reward claim."
@ar1ls

**Comment by ar1ls** [comment]
> @lucyfyy 

yep
at the moment there are two methods in the library, one returns an error, the second shows a phantom reward collection, but it does not actually happen, it was found out by the "poke" method that, once every 3-4 days, the same "captcha" appears on the hoylab. At the moment I'm looking for a way to get around it
