### ISSUE TITLE
Geetest verification during daily reward claim.

### ISSUE THREAD

**Issue by ashleney** [seriaati/genshin.py#134]
A fair while ago hoyo introduced Geetest human verification (similar to for example Google's Recaptcha). This means that daily reward claiming could only be automated if a human solved a puzzle.

This month Geetest verification has also been introduced to hoyolab and with that also to genshin.py. Now when a human verification is encountered an error is raised and the request must be remade with a solved challenge. Most of the time services like [2captcha](https://2captcha.com) are utilized but they quickly get expensive and are frankly not too ethical

```py
try:
	client.claim_daily_reward()
except genshin.errors.GeetestTriggered as e:
    solved = <some third party tool>(gt=e.gt, challenge=gt.challenge)
    client.claim_daily_reward(challenge=solved)
```

The current goal is to introduce a built-in image recognition software (which might not really be realistic) or integrate some captcha-solving services (though as I said I have some ethical qualms about this).

Currently, I recommend simply getting rid of automated daily reward claiming altogether. The measly rewards are frankly not enough to warrant paying for 3rd party services.

**Comment by mafuyuuu1** [comment]
Is this still a problem until now?

**Comment by seriaati** [comment]
seems like it is gone.

**Comment by mafuyuuu1** [comment]
> seems like it is gone.

Yeah. I'm using this for a week and I don't see one though so maybe it's gone now.

**Comment by BobbyWibowo** [comment]
Yeah my automated one had stopped triggering captcha since early September actually, not even once since then

For context it used to trigger it daily throughout the entirety of July and August

No issue on HSR and HI3 either

**Comment by seriaati** [comment]
Closing since this no longer appears, additionally a check was implemented to raise an error when geetest is triggered.
