### ISSUE TITLE
Seemingly incompatible with the newest version of pydantic

### ISSUE THREAD

**Issue by Richard-W0** [seriaati/genshin.py#140]
Even the most basic functions give the error "Exception has occurred: PydanticUserError
If you use `@root_validator` with pre=False (the default) you MUST specify `skip_on_failure=True`. Note that `@root_validator` is deprecated and should be replaced with `@model_validator`."

**Comment by ashleney** [comment]
Works on the github version, seems like pypi release is behind. I'll make a new release

**Comment by ashleney** [comment]
Long overdue anyways

**Comment by ShresthVaibhav** [comment]
> Even the most basic functions give the error "Exception has occurred: PydanticUserError If you use `@root_validator` with pre=False (the default) you MUST specify `skip_on_failure=True`. Note that `@root_validator` is deprecated and should be replaced with `@model_validator`."

try pydantic==1.10.9

**Comment by seriaati** [comment]
just to clarify everything, the latest version of genshin.py (1.6.1) supports both pydantic v1 and v2.

**Comment by seriaati** [comment]
Closing this as the issues no longer persists, genshin.py is compatible with Pydantic v1 and v2.
We will try to migrate to v2 fully one day, but that's too much hassle tbh.
