### ISSUE TITLE
get_banner_details still returns 4.0 first phase banners

### ISSUE THREAD

**Issue by emredesu** [seriaati/genshin.py#143]
Hey! It seems like the API is no longer returning the up-to-date banners, it seems to be stuck on Lyney-Yelan banners. Here's how the output looks:

```
async def getbanners():
    banners = await client.get_banner_details(game = genshin.types.Game.GENSHIN)
    for banner in banners:
    print(banner.name)

>>> asyncio.run(getbanners())
Standard Wish "Wanderlust Invocation"
Event Wish "Conjuring Chiaroscuro"
Event Wish "Discerner of Enigmas"
Event Wish "Epitome Invocation"
```

"Conjuring Chiaroscuro" is the Lyney banner, which should have been gone a few days ago.

**Comment by ashleney** [comment]
Yeah looks like hoyo stopped updating that endpoint, gotta hope it comes to enka.

**Comment by emredesu** [comment]
I've started extracting the banner data links from the in-game client and reading them from a gist myself. I will be updating this with every banner, you could use [my gist](https://gist.github.com/emredesu/786b47a49442c497b050630e8b218b5d) in the meanwhile if you'd like.

**Comment by EffortlessFury** [comment]
The endpoint [moved,](https://operation-webstatic.mihoyo.com/gacha_info/hk4e/cn_gf01/gacha/list.json) I think.

**Comment by emredesu** [comment]
Yep I've been using that endpoint over manually updating my gist too, works wonderfully.
