### ISSUE TITLE
Cookies are not valid

### ISSUE THREAD

**Issue by MIPOHBOPOHIH** [seriaati/genshin.py#149]
Lately when I try to log in using my cookies, I get an error: 
genshin.errors.InvalidCookies: [-100] Cookies are not valid.

I've tried getting cookies through hoyolab.com and py -m genshin login, but nothing works. I tried passing cookies immediately when creating a client, and using the set_cookies method.

**Comment by kgirtxd** [comment]
A few questions for you.

1. What region is the account in?
2. When does it give you the error? is it when the client is made or when running the next command? (what command?)
3. Have you gotten a fresh set of cookies since the errors started?

**Comment by MIPOHBOPOHIH** [comment]
> A few questions for you.
> 
> 1. What region is the account in?
> 2. When does it give you the error? is it when the client is made or when running the next command? (what command?)
> 3. Have you gotten a fresh set of cookies since the errors started?

1. Europe? (Russia)
2. Try to run next command. I think every command is "broken" (try to use it with get_genshin_user)
3. yes, sure
![image](https://github.com/thesadru/genshin.py/assets/98014624/6ddb681a-74ea-4ef4-8ddb-d9944b5c99ee)
![image](https://github.com/thesadru/genshin.py/assets/98014624/ec06fc16-c739-4ad4-b39d-4d83104b1616)

**Comment by kgirtxd** [comment]
I ran that UID with one of my cookies and got 52 characters.
Assuming your cookies are stored in a dict that should work if all the needed keys are present.

I would go fetch new cookies and try sending all the available keys.  Some regions are starting to require the v2 version of things.

**Comment by MIPOHBOPOHIH** [comment]
i try to use ltoken_v2 and it doesn't work too

**Comment by MIPOHBOPOHIH** [comment]
i try to delete cookies in browser and fetch it again, and it doesn't work

**Comment by seriaati** [comment]
how are you entering your cookies

**Comment by seriaati** [comment]
if you're passing in a dictionary, use the same keys that you found in the cookies, for example if the cookie says `ltuid_v2`, then pass in `{"ltuid_v2": ...}`

**Comment by MIPOHBOPOHIH** [comment]
> how are you entering your cookies

try `py -m genshin login` and try to get cookies from `F12 - Application`

**Comment by MIPOHBOPOHIH** [comment]
> if you're passing in a dictionary, use the same keys that you found in the cookies, for example if the cookie says `ltuid_v2`, then pass in `{"ltuid_v2": ...}`

it doesnt work too

**Comment by kgirtxd** [comment]
Can you give us a list of the keys you are getting from F12 - Application?

**Comment by seriaati** [comment]
hm, can you join the discord server https://discord.gg/6P25ZGVyQd
so it's easier for us to figure this out?

**Comment by kgirtxd** [comment]
Solved in Discord
"So, it turns out that the problem is now in my code, which I'm surprised at, since it worked fine for about a week"
