### ISSUE TITLE
Custom cache aioredis problem and Fixed

### ISSUE THREAD

**Issue by sirilerklab** [seriaati/genshin.py#15]
I tried custom cache with docs this: 
https://github.com/thesadru/genshin.py/blob/master/docs/caching.md#custom-caches

But I got this
![image](https://user-images.githubusercontent.com/24217516/151853205-820ea999-b23c-4e49-84d5-e521d6cf85b5.png)

And I added await after self.redis but I got error this:
![image](https://user-images.githubusercontent.com/24217516/151853537-516a8702-bb55-47cd-b9b6-90c3423e8734.png)

But I have fixed with using "msgpack" to pack JSON data
```python
import msgpack

async def _check_cache(self, key, check, lang):
        """Check the cache for any entries"""
        key = ":".join(map(str, key + (lang or self.lang,)))

        data = await self.redis.get(key)

        if data is None:
            return None

        if check is None or check(data):
            return msgpack.unpackb(data)

        await self.redis.delete(key)

        return None

    async def _update_cache(self, data, key, check=None, lang=None) -> None:
        """Update the cache with a new entry"""
        key = ":".join(map(str, key + (lang or self.lang,)))

        if check is not None and not check(data):
            return

        await self.redis.set(key, msgpack.packb(data), ex=3600)
```

Result:
![image](https://user-images.githubusercontent.com/24217516/151854084-ce22510f-c081-4958-897e-75365e9fde81.png)

**Comment by ashleney** [comment]
I'm open to changing the documentation to recommend msgpack, but I'd still rather keep the potential dependencies to a minimum, so I'll probs just use JSON in the example itself. 

tbh I feel that custom caches are not at all user-friendly atm. They're gonna need some rewrite for sure.

**Comment by sirilerklab** [comment]
If you're not add dependencies. You can use built-on library like JSON.

```python
import asyncio
import json
import aioredis

async def main():
    # Connect redis
    redis = await aioredis.from_url("redis://localhost:6379/0")

    # Set foo value {"bar": 1} without using msgpack
    await redis.set("foo", json.dumps({"test": 1}), ex=150)

    # Get foo
    foo = await redis.get("foo")

    # Covert string to JSON
    foo = json.loads(foo)

    print(foo)

asyncio.run(main())
```
![image](https://user-images.githubusercontent.com/24217516/151998130-34368149-2e9c-460d-9c26-b65e3e18e70c.png)

**Comment by ashleney** [comment]
oops I forgot about this issue
