### ISSUE TITLE
JS version

### ISSUE THREAD

**Issue by SuperZombi** [seriaati/genshin.py#153]
Hello. I made a plugin for obtaining original resin in the browser (it’s not convenient for me to do this from my phone).
But after replit became paid, my server no longer works.
I'm now trying to rewrite my program in pure JS.
This code works fine in Python, but doesn't want to work in JS.
```python
import requests
USER_AGENT = {'User-Agent': "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36"}
cookies = {
    "ltuid_v2": _,
    "ltoken_v2": _,
    "ltmid_v2": _
}
r = requests.get("https://api-os-takumi.mihoyo.com/binding/api/getUserGameRolesByCookie", headers=USER_AGENT, cookies=cookies)
print(r.status_code)
data = r.json().get('data')
print(data.get('list'))
```
It says that you cannot set cookies in xhr to a third-party server.
```javascript
let xhr = new XMLHttpRequest();
xhr.open("GET", "https://api-os-takumi.mihoyo.com/binding/api/getUserGameRolesByCookie", true)
xhr.withCredentials = true;
// xhr.setRequestHeader("Credentials", 'include')
// xhr.setRequestHeader("Access-Control-Allow-Origin", "https://www.hoyolab.com")
// xhr.setRequestHeader("Access-Control-Allow-Credentials", true)
// xhr.setRequestHeader("Origin", "https://act.hoyolab.com")
// xhr.setRequestHeader("Referer", "https://act.hoyolab.com")
// xhr.setRequestHeader('Cookie', 'ltuid_v2=_; ltoken_v2=_; ltmid_v2=_');
// xhr.setRequestHeader('Set-Cookie', 'ltuid_v2=_; ltoken_v2=_; ltmid_v2=_');
xhr.onload = _=>{
	if (xhr.status == 200){
		let answer = JSON.parse(xhr.response);
		console.log(answer)
	}
}
xhr.send()
```
![image](https://github.com/thesadru/genshin.py/assets/75096786/26b5fefc-19c6-4df6-999c-6251e52445b6)

![image](https://github.com/thesadru/genshin.py/assets/75096786/1e0438f3-4355-4ec0-a93a-e9c83c1e680a)

![image](https://github.com/thesadru/genshin.py/assets/75096786/92616d46-bcb1-4205-be8b-4a67c29c592b)

### Can someone help me pleeeeease

<img height="144px" src="https://github.com/thesadru/genshin.py/assets/75096786/8bbe6384-6e9e-46ac-af23-d453bc3f85ab">

**Comment by teehee567** [comment]
Dont use xhr request just use a normal fetch

**Comment by SuperZombi** [comment]
fetch also sends requests without cookies
```javascript
fetch("https://api-os-takumi.mihoyo.com/binding/api/getUserGameRolesByCookie", {
	// credentials: 'same-origin',
	credentials: 'include',
	headers: {
		Cookie: 'ltuid_v2=_; ltoken_v2=_; ltmid_v2=_'
	}
}).then(response => response.json()).then(data => console.log(data));
```
![image](https://github.com/thesadru/genshin.py/assets/75096786/d25899c2-7595-494b-b795-3878da855d18)

![image](https://github.com/thesadru/genshin.py/assets/75096786/9c5c1d3b-053f-4be6-8af0-d9f09496cac4)

**Comment by teehee567** [comment]
> fetch also sends requests without cookies
> 
> ```javascript
> 
> fetch("https://api-os-takumi.mihoyo.com/binding/api/getUserGameRolesByCookie", {
> 
> 	// credentials: 'same-origin',
> 
> 	credentials: 'include',
> 
> 	headers: {
> 
> 		Cookie: 'ltuid_v2=_; ltoken_v2=_; ltmid_v2=_'
> 
> 	}
> 
> }).then(response => response.json()).then(data => console.log(data));
> 
> ```
> 
> ![image](https://github.com/thesadru/genshin.py/assets/75096786/d25899c2-7595-494b-b795-3878da855d18)
> 
> 
> 
> ![image](https://github.com/thesadru/genshin.py/assets/75096786/9c5c1d3b-053f-4be6-8af0-d9f09496cac4)

It worked tour cookies are invalid, check or regenerate your cookies if that doesnt work check if you need headers like xpc

**Comment by SuperZombi** [comment]
> It worked your cookies are invalid, check or regenerate your cookies if that doesnt work check if you need headers like xpc

1. It's not working, because there are no cookies in request header. 
2. My cookies correct, cuz it's working with Python.
3. What is xpc?

**Comment by teehee567** [comment]
Chat gpt and copy the code

**Comment by ashleney** [comment]
@SuperZombi May I ask how you are resolving CORS? Seems to be related to that.

@teehee567 Telling someone to use ChatGPT is not really helpful, especially not for debugging.

**Comment by teehee567** [comment]
> @SuperZombi May I ask how you are resolving CORS? Seems to be related to that.
> 
> 
> 
> @teehee567 Telling someone to use ChatGPT is not really helpful, especially not for debugging.

Mb more useful tgan saying nothing

**Comment by SuperZombi** [comment]
> How you are resolving CORS? Seems to be related to that.

Hmm. idk. i know that cors need to be specified on server side, to allow access from another domains.
But the problem is that the browser does not allow sending a request with cookies for another domain.

**Comment by ashleney** [comment]
The browser does allow sending cookies but they must not be sameSite and you must explicitly say you want them sent. I'm pretty sure setting them as a header shouldn't be possible, since they can only be sent when they are actual cookies stored in the browser but don't quote me on that.

**Comment by SuperZombi** [comment]
Maybe the problem is that it is chrome extension for hoyolab?

upd: No. cuz it was working, when i sent requests to my repl server.
But I haven't used cookies. I simply have been sending tokens via url search query.

**Comment by SuperZombi** [comment]
OK. I finally did it.
You need to add `"permissions": ["cookies"]` to your manifest and create a service worker.
<details>

`background.js`:
```javascript
chrome.runtime.onMessage.addListener((request, sender, sendResponse) => {
	if (request.type == "getOriginalResin"){
		for (const [key, value] of Object.entries(request.cookies)) {
			chrome.cookies.set({
				"url": "https://api-os-takumi.mihoyo.com/",
				"name": key,
				"value": value
			});
		}
		fetch('https://api-os-takumi.mihoyo.com/binding/api/getUserGameRolesByCookie')
		.then((response) => response.json())
		.then((answer) => {
			if (answer.data){
				sendResponse({...})
			}
		})
		return true
	}
});
```
`scripts.js`:
```javascript
chrome.runtime.sendMessage({type: "getOriginalResin",
	cookies: {
		ltuid_v2: ltuid,
		ltmid_v2: ltmid,
		ltoken_v2: ltoken
	}
}, (response) => {...})
```
</details>
<hr>

But now, I am faced with the question of how to correctly make a request for original resin.
```python
client.get_notes(account.uid)
```

I tried to understand the source code and this is what I managed to do:
```python
import requests
UID = ""
url = f"https://bbs-api-os.hoyolab.com/game_record/genshin/api/dailyNote?role_id={UID}&server=os_euro"

USER_AGENT = {'User-Agent': "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36"}
cookies = {
    "ltmid_v2": "_",
    "ltoken_v2": "_",
    "ltuid_v2": "_",
}
r = requests.get(url, headers=USER_AGENT, cookies=cookies)
print(r.status_code)
print(r.json())
```

But it doesn't work:
```
200
{'data': None, 'message': 'invalid request', 'retcode': -10001}
```

I'm trying to do that in Python first, but then I'll rewrite this code in JS.

**Comment by teehee567** [comment]
> OK. I finally did it.
> 
> You need to add `"permissions": ["cookies"]` to your manifest and create a service worker.
> 
> <details>
> 
> 
> 
> `background.js`:
> 
> ```javascript
> 
> chrome.runtime.onMessage.addListener((request, sender, sendResponse) => {
> 
> 	if (request.type == "getOriginalResin"){
> 
> 		for (const [key, value] of Object.entries(request.cookies)) {
> 
> 			chrome.cookies.set({
> 
> 				"url": "https://api-os-takumi.mihoyo.com/",
> 
> 				"name": key,
> 
> 				"value": value
> 
> 			});
> 
> 		}
> 
> 		fetch('https://api-os-takumi.mihoyo.com/binding/api/getUserGameRolesByCookie')
> 
> 		.then((response) => response.json())
> 
> 		.then((answer) => {
> 
> 			if (answer.data){
> 
> 				sendResponse({...})
> 
> 			}
> 
> 		})
> 
> 		return true
> 
> 	}
> 
> });
> 
> ```
> 
> `scripts.js`:
> 
> ```javascript
> 
> chrome.runtime.sendMessage({type: "getOriginalResin",
> 
> 	cookies: {
> 
> 		ltuid_v2: ltuid,
> 
> 		ltmid_v2: ltmid,
> 
> 		ltoken_v2: ltoken
> 
> 	}
> 
> }, (response) => {...})
> 
> ```
> 
> </details>
> 
> <hr>
> 
> 
> 
> But now, I am faced with the question of how to correctly make a request for original resin.
> 
> I tried to understand the source code and this is what I managed to do:
> 
> ```python
> 
> import requests
> 
> UID = ""
> 
> url = f"https://bbs-api-os.hoyolab.com/game_record/genshin/api/dailyNote?role_id={UID}&server=os_euro"
> 
> 
> 
> USER_AGENT = {'User-Agent': "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36"}
> 
> cookies = {
> 
>     "ltmid_v2": "_",
> 
>     "ltoken_v2": "_",
> 
>     "ltuid_v2": "_",
> 
> }
> 
> r = requests.get(url, headers=USER_AGENT, cookies=cookies)
> 
> print(r.status_code)
> 
> print(r.json())
> 
> ```
> 
> But it doesn't work:
> 
> ```
> 
> 200
> 
> {'data': None, 'message': 'invalid request', 'retcode': -10001}
> 
> ```
> 
> 
> 
> I'm trying to do that in Python first, but then I'll rewrite this code in JS.

You need xrpc headers if you join the discord you can get faster responces from more people btw. If youre looking for events and other specific endpoints that isnt in genshinpy someone in the discord will probably have it

Anyway there are only 3 headers you need or you can copy from genshinpy default headers

```rust
  headers.insert("x-rpc-app_version", HeaderValue::from_static("1.5.0"));
        headers.insert("x-rpc-client_type", HeaderValue::from_static("5"));
        headers.insert("x-rpc-language", HeaderValue::from_static("en-us"));
```

These are the ones i use but you can find genshinpys ones somewhere in the source code im on phone so i cant go get it you should be able to just search x-rpc in the repository to find it

**Comment by SuperZombi** [comment]
> You need xrpc headers

Tnx. Now the final code is:

```python
HEADERS = {
    'User-Agent': "_",
    "x-rpc-client_type": "5",
    "x-rpc-app_version": "1.5.0",
    "ds": generate_dynamic_secret()
}
```
and i need to translate this function to JS 💀

**Comment by SuperZombi** [comment]
IT WORKS! Thanks everyone for help
<details>
<summary> generate_dynamic_secret function in JS</summary>

```javascript
function generate_dynamic_secret(salt="6s25p5ox5y14umn1p61aqyyvbvvl3lrt"){
	let t = Math.floor(Date.now() / 1000);
	let r = Array.from({ length: 6 }, () => Math.random().toString(36)[2]).join('');
	let data = `salt=${salt}&t=${t}&r=${r}`;
	let hash = MD5(data);
	return `${t},${r},${hash}`;
}
```
</datails>
