### ISSUE TITLE
Accessing a cookie manager's `user_id` property may raise an error

### ISSUE THREAD

**Issue by theseanl** [seriaati/genshin.py#154]
https://github.com/thesadru/genshin.py/blob/5570643029fcd376cd0677ed6ce5c577410d559a/genshin/client/manager/managers.py#L252

This line may throw an error if the associated cookie value is the empty string. It'd be nice if some type checking is added here.

**Comment by jokelbaf** [comment]
But why would the value be an empty string? Unless you set it yourself this way

**Comment by theseanl** [comment]
Indeed, I guess it can be an error that should be fixed from a downstream code, but it is unclear to consumers of the code that certain cookie values need to be a decimal representation of an integer, and otherwise the code will fail in an obscure way. A basic type checking and discarding a cookie if it doesn't pass would be nice, it took awhile to debug this issue..

**Comment by jokelbaf** [comment]
This does not sound like an issue with the library but rather with your code. Although this type check could be implemented, I'm not sure. Need to know @thesadru's opinion on this

**Comment by ashleney** [comment]
Yeah extra validation shouldn't hurt, I'd have no problem with implementing some clearer error.
