### ISSUE TITLE
Star Rail - Add MoC and PF cycle count to the floors

### ISSUE THREAD

**Issue by kgirtxd** [seriaati/genshin.py#159]
The HoYoLab website and app display the cycles used for each floor 

![image](https://github.com/thesadru/genshin.py/assets/15676362/6f3f9ced-bb25-4e07-aa1f-bc8207e366e5)

**Comment by kgirtxd** [comment]
NVM its there just named something not obvious

**Comment by ashleney** [comment]
Might be smart to alias them
