### ISSUE TITLE
Honkai Star Rail - Real-time notes

### ISSUE THREAD

**Issue by sanioooook** [seriaati/genshin.py#169]
Can you add please real time notes (like for tht Genshin Impact with resin, commissions and etc.) for Honkai Star Rail and also add it to the CLI?

**Comment by seriaati** [comment]
We already have real-time notes for HSR, not in the CLI tho just as a method in the client.

**Comment by sanioooook** [comment]
then please add them to the CLI

**Comment by seriaati** [comment]
tbh i've never used the CLI myself, i also don't even know how it works
sorry but i currently dont plan to work on it, maybe someone else would
