### ISSUE TITLE
Opening Cookies in Browser using Linux or Ubuntu

### ISSUE THREAD

**Issue by rafieakmal** [seriaati/genshin.py#175]
Hello, I got this error while I want to log in using my email and password using the Ubuntu terminal server, but the message only shows like this
![Screenshot 2024-04-02 145021](https://github.com/thesadru/genshin.py/assets/100586114/2f50ffcd-c8e2-4c4c-a9ad-b6cfd8738230)
and not open the browser as it should

Thanks

**Comment by seriaati** [comment]
Try typing the url manually in your browser.

**Comment by jokelbaf** [comment]
This seems like an issue with `webbrowser` rather than `genshin.py`, as that's what we're using to open the browser automatically

**Comment by seriaati** [comment]
Did it work?

**Comment by rafieakmal** [comment]
> Try typing the url manually in your browser.

it worked thanks

**Comment by rafieakmal** [comment]
Case closed
