### ISSUE TITLE
Provide entry points in metadata for the CLI

### ISSUE THREAD

**Issue by FichteFoll** [seriaati/genshin.py#177]
Currently, `genshin.py` cannot be installed using `pipx`, most likely because it is missing an `entry_points` keyword for setuptools's `setup` method (or `project.scripts` section inside pyproject.toml). See also [the documentation](https://setuptools.pypa.io/en/latest/userguide/entry_point.html).

The exact output of pipx is as follows:

```
$ pipx install 'genshin[cli]'

No apps associated with package genshin or its dependencies. If you are attempting to install a library, pipx should not be used. Consider using pip or a similar tool instead.
```

Also, once this is done, perhaps mentioning this usage in the docs's CLI page is warranted.

**Comment by ashleney** [comment]
Genshin.py is primarily a library, the CLI is only for getting cookies and quick tests. It was never meant to be used as an actual CLI tool and definitely was not intended to be used in isolated envrionments such as the one pipx provides.
