### ISSUE TITLE
404 on gacha information

### ISSUE THREAD

**Issue by yabb85** [seriaati/genshin.py#189]
Hi,

Since today my request on gacha information return issue because the link return 404 error.
I fix this by replacing
`genshin="https://hk4e-api-os.hoyoverse.com/event/gacha_info/api/"`
with
` genshin="https://hk4e-api-os.hoyoverse.com/gacha_info/api/"`

**Comment by jokelbaf** [comment]
I noted the url change a while ago but did not bother with updating it since everything had been working fine. Fixed on `master` branch, thanks for pointing this out!
