### ISSUE TITLE
"'MultiCookieClient' object has no attribute 'calculate'"

### ISSUE THREAD

**Issue by ahmadkeren** [seriaati/genshin.py#19]
Excuse me, that work perfectly before.. but recently that error shown..
![Screen Shot 2022-02-21 at 09 13 03](https://user-images.githubusercontent.com/49072140/154877828-62e13717-5f8d-4da6-a2f6-3d5f135ddb86.png)
![Screen Shot 2022-02-21 at 09 13 13](https://user-images.githubusercontent.com/49072140/154877849-d29af00d-768a-405f-8dbe-78004be88eae.png)

Thanks

**Comment by ashleney** [comment]
`calculate` has been removed in favor of a more clean `calculator` which now uses builders.

https://thesadru.github.io/genshin.py/calculator/

Considering `calculate` was experimental I thought it would be better to just remove it completely. You can pin genshin.py to the previous version if you don't feel like rewriting anything yet.
