### ISSUE TITLE
Implement the Traveler's Diary

### ISSUE THREAD

**Issue by ashleney** [seriaati/genshin.py#2]
The Traveler's Diary has been available in the hoyolab app for a while now.
Chinese users had it for some time already, as proved by https://github.com/hyhAsma/Genshin_id_inquiry/commit/904441a399874295a9e0b16125cae3f7012bfe7d
Implementations of it already exist (for example [Snap.Genshin](https://github.com/DGP-Studio/DGP.Genshin.MiHoYoAPI/tree/main/Journey)) but there don't seem to be any for overseas players.

This has been addressed before in https://github.com/thesadru/genshinstats/issues/18 but the endpoint has been falsely identified as the endpoint for transaction logs.

This task would've ordinarily been very simple however this data is only visible from the app. This requires reverse-engineering the app itself which has been done for the Chinese Miyoushe app but not for the Overseas Hoyolab one. I will be attempting to somehow intercept requests but I do not have any experience with reverse-engineering apps so I would gladly appreciate any help.

PS: Chinese users may already use this feature thanks to 1600940.

**Comment by CustomIcon** [comment]
![Screenshot_2021-10-28-14-40-21-325_com guoshi httpcanary](https://user-images.githubusercontent.com/43902347/139230675-ff16b643-a03e-4a83-9a63-2218204e93ac.jpg)
you mean this?

edit: i had to use an http proxy to fetch endpoints might be helpful

**Comment by CustomIcon** [comment]
![IMG_20211028_144656](https://user-images.githubusercontent.com/43902347/139231875-978da7a6-59ac-4ca7-a2ee-5079e533e34a.jpg)
![Screenshot_2021-10-28-14-46-27-906_com guoshi httpcanary](https://user-images.githubusercontent.com/43902347/139231890-de92ca35-006b-45eb-88fb-f6e8eba99d3e.jpg)
soo. yeah here you go

**Comment by ashleney** [comment]
Oh yeah, that's the one. What did you do to be able to see the entire request? I swear everything I tried failed because I couldn't intercept the https request before it's been encrypted so I could only ever see the domain.

The first one is the real-time notes, that one is already implemented.

**Comment by CustomIcon** [comment]
i used http Canary. i have a modded apk for myself that has removed tracking and ads, and fixed certificate to capture http and tcp request from any app. you can contact me through telegram https://t.me/CustomIcon and ill give you instructions on how to get it work, or help you with those requests since i have a rooted phone
