### ISSUE TITLE
Support for IOS

### ISSUE THREAD

**Issue by champymarty** [seriaati/genshin.py#20]
It is more a question than a real issue.
I was just wondering if it is possible to get the url in any way in ios.

Thank you !

**Comment by ashleney** [comment]
paimon.moe recommends this:

4. Download Stream on App Store [here](https://apps.apple.com/app/stream/id1312141691)
5. Open the app, then allow VPN in system preferences (Settings > General > VPN)
6. Install CA (click Sniff Now on Stream App > Install CA > A pop up window will appear and choose allow > Now CA is downloaded
7. Go to Settings > General > VPN & Device management > Click on Stream Generated CA and install
8. Open Genshin Impact then open Wish screen, stay on that page
9. Back to Stream App > Choose I've trusted > Tap Sniff Now Button
10. Back to Genshin Impact then open the Wish history page
11. Wait for page to load
12. Back to Stream App > Stop Sniffing
13. Click Sniff History > Choose a request that ends by .json (the link start with https://hk4e-api-os.mihoyo.com/)
14. Click Request tab, then copy the link and paste it below
- If you got any problem, see troubleshooting guide [here](https://docs.google.com/document/d/1U8pf9lqKALtMSWI11t_6npYlVOCpIFZZRvhrC_9-2ek/edit)

**Comment by CustomIcon** [comment]
![image](https://user-images.githubusercontent.com/43902347/161013194-9771f46f-452f-46be-83f8-615e514bf8d6.png)
weird... ill look into this one. https sniffing on ios gonna be harder than this

**Comment by CustomIcon** [comment]
okay i found a very effective method other than using stream app

**Comment by champymarty** [comment]
How do you do it ?

**Comment by CustomIcon** [comment]
> How do you do it ?
> 
> 

you need to install vpn profile of stream app.

go to certificate trust settings and turn on stream certificate toggle there.

and you can decrypt ssl from stream app

**Comment by champymarty** [comment]
thanks !
