### ISSUE TITLE
Add daily rewards for ZZZ

### ISSUE THREAD

**Issue by TheraNinjaCat** [seriaati/genshin.py#201]
A cursory look at the network tab during ZZZ daily reward claim suggests that there's nothing significantly different from the Genshin or StarRail ones.

**Comment by seriaati** [comment]
See https://github.com/thesadru/genshin.py/pull/200

**Comment by seriaati** [comment]
You can try it out now by installing the dev branch version of genshin.py

**Comment by rennerdo30** [comment]
I just tried the dev version, but got the following error:

```
Traceback (most recent call last):
...
  File "...\venv\Lib\site-packages\genshin\client\components\daily.py", line 172, in claim_daily_reward
    await self.request_daily_reward("sign", method="POST", game=game, lang=lang, challenge=challenge)
  File "...\venv\Lib\site-packages\genshin\client\components\daily.py", line 47, in request_daily_reward
    base_url = routes.REWARD_URL.get_url(self.region, game)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "...\venv\Lib\site-packages\genshin\client\routes.py", line 101, in get_url
    raise RuntimeError(f"URL does not support {game.name} game for {region.name} region.")
RuntimeError: URL does not support ZZZ game for OVERSEAS region.
```
My game version is the global one. I play on the european-server.

**Comment by rennerdo30** [comment]
I just tried the dev branch, but get the following exception: 
```
2024-07-06 12:30:27,999 - ERROR - Could not claim daily check-in rewards for Zenless Zone Zero: URL does not support ZZZ game for OVERSEAS region.
```

Also trying to redeem a code results in:
```
2024-07-06 12:30:42,505 - ERROR - Could not redeem code ZENLESSGIFT: Game.ZZZ does not support code redemption.
```

**Comment by TheraNinjaCat** [comment]
Are you absolutely sure you've checked out the dev branch and are actually running that version of the library? I just tested the dev branch with a simple

```
import genshin
client = genshin.Client()
client.set_cookies(...)
await client.claim_daily_reward(game=genshin.Game.ZZZ)
```

and it worked perfectly fine when I had checked out and run `pip install .` on the dev branch. I ran the same code after checking out and running `pip install .` on the master branch however and I got the exact error you've experienced (`RuntimeError: URL does not support ZZZ game for OVERSEAS region.`). My account is in the Asia region for what it's worth.

I can't speak to the code redeem, I'm not familiar in the slightest with that code.

**Comment by rennerdo30** [comment]
> Are you absolutely sure you've checked out the dev branch and are actually running that version of the library? I just tested the dev branch with a simple
> 
> ```
> import genshin
> client = genshin.Client()
> client.set_cookies(...)
> await client.claim_daily_reward(game=genshin.Game.ZZZ)
> ```
> 
> and it worked perfectly fine when I had checked out and run `pip install .` on the dev branch. I ran the same code after checking out and running `pip install .` on the master branch however and I got the exact error you've experienced (`RuntimeError: URL does not support ZZZ game for OVERSEAS region.`). My account is in the Asia region for what it's worth.
> 
> I can't speak to the code redeem, I'm not familiar in the slightest with that code.

Thanks for taking your time to answer. I've already deleted my comment, since I realized, that pip did not update the package, since it was already installed. This was an error on my side, hence I already deleted my comment. 

using this command resolved the issue for me:
```
pip install  --upgrade --force-reinstall git+https://github.com/thesadru/genshin.py@dev
```

**Comment by seriaati** [comment]
Dev changes are now merged into master, you can use the master branch instead.
