### ISSUE TITLE
Notes.remaining_transformer_recovery_time only returns the remaining days

### ISSUE THREAD

**Issue by emredesu** [seriaati/genshin.py#218]
As mentioned in the title, getting `Notes.remaining_transformer_recovery_time` from Genshin real-time notes only returns the remaining days - hours, minutes and seconds will always be zero. For example, I just did my Parametric Transformer and the timedelta object returns `6 days, 0:00:00`, not giving any information other than the remaining days.

Similarly, trying to get the remaining duration using `Notes.transformer_recovery_time` returns a `datetime` that points to exactly remaining days later, so doing something like `Notes.transformer_recovery_time - datetime.datetime.now()` will also result in something like `6 days, 0:00:00`.

If it's not possible to obtain data other than the remaining days, renaming of the field to something like `days_until_transformer_recovery` would be more intuitive.

**Comment by seriaati** [comment]
Discussion happened in the [Discord server](https://discord.com/channels/570841314200125460/803293168132947968/1274656430552776809)
