### ISSUE TITLE
Geetest triggered during the battle chronicle API request

### ISSUE THREAD

**Issue by sanioooook** [seriaati/genshin.py#228]
When calling the `get_imaginarium_theater()` or `get_genshin_spiral_abyss()` function, I get the error `[10035] Geetest triggered during the battle chronicle API request.` but the problem is not the error itself, but that there is no way to solve it, although geetest can be solved for `claim_daily_reward()`. Is it possible to do a similar behavior for the `get_imaginarium_theater()` and `get_genshin_spiral_abyss()` functions?

**Comment by seriaati** [comment]
Generate geetest using the `create_mmt()` method then solve it and then pass the result to `verify_mmt()` method

**Comment by sanioooook** [comment]
how do I get the [required](https://2captcha.com/api-docs/geetest#geetesttaskproxyless-task-type-specification) parameter (full url) to solve the captcha?

**Comment by seriaati** [comment]
as I said, use the `create_mmt()` method

**Comment by sanioooook** [comment]
Thank you, this helped me
