### ISSUE TITLE
Unable to get the authkey from logfiles after 2.6

### ISSUE THREAD

**Issue by champymarty** [seriaati/genshin.py#23]
Since the ayato update, the link use to get the wish history on PC is no longer getting generated in the log file :(((

**Comment by ashleney** [comment]
I am unable to reproduce this issue. May I get some more information?

The only similar issue I could find in any other projects interacting with the genshin gacha API is https://github.com/biuuu/genshin-wish-export/issues/120 and that doesn't help much either.

**Comment by champymarty** [comment]
Sorry about that I tried again to show you, but now it is working again. The last time I opened the game it downlaoded something, maybe it fixed it. I was searching for OnGetWebViewPageFinish in the log file but if was never there for a least a week, even when opening the wish history in game. Sorry for your time and thank you !
