### ISSUE TITLE
Add Deadly Assault, Lost Void, and Withered Domain

### ISSUE THREAD

**Issue by sanioooook** [seriaati/genshin.py#231]
Please, update models for ZZZ (add new abyss, change hollow zero endpoint and etc.)

**Comment by seriaati** [comment]
I don't have data of Deadly Assault yet, what do you mean by "change hollow zero endpoint" and "etc."? Please make your request more specific.

**Comment by sanioooook** [comment]
when receiving data about the zero hollow (using your code. _sorry, I do not know what to call it better: library/module/bot?_) I got empty data. after this i open [website](https://act.hoyolab.com/app/zzz-game-record/index.html) and opening the developer tools, I noticed that this data is obtained by a separate request and the endpoint (where the request is sent) is very similar to what they added after the update (I don't remember how it was before, but in the code I didn't find anything similar to abyss_abstract)

endpoint with hollow zero (new name city of withering)
![image](https://github.com/user-attachments/assets/92c843da-88be-4eb6-a9cb-eac2c8c90653)

new endpoint with lost abyss
![image](https://github.com/user-attachments/assets/36bba9f0-3ef8-4146-b17e-cea8356521a8)

**Comment by seriaati** [comment]
genshin.py currently supports neither withered domain (`abyss_abstract`) nor lost void (`abyss2_abstract`)...
I'm not sure what "code" you're mentioning to is, either way, I can add support for these, just need some time to play the game and gather the data.
Will add support to these:
- [x] Deadly Assault
- [x] Lost Void
- [ ] Withered Domain

It seems like you're familiar with DevTools and request intercepting though, I would appreciate a lot if you add the models yourself and open a PR 😆

**Comment by sanioooook** [comment]
sorry, python is a Greek for me, in which gpt chat helps me and the experience from js to write something in python for myself, so I'm not sure what I'll be able to do. instead, I can try to provide you with json (without values, but with an explanation of which field is responsible for what and what type it is)

**Comment by sanioooook** [comment]
## Withered Domain (https://sg-public-api.hoyolab.com/event/game_record_zzz/api/zzz/abyss_abstract?server=&role_id=)
```json
{
    "retcode": "number",
    "message": "string",
    "data": {
        "abyss_level": {
            "cur_level": "number", // Current level in the abyss.
            "max_level": "number", // Maximum level in the abyss.
            "icon": "string" // URL icon.
        },
        "abyss_point": { // it will be equal to 0, since this content has moved to Lost Void
            "cur_point": "number", // Current points.
            "max_point": "number" // Maximum points.
        },
        "abyss_duty": "null", // not sure that is mean.
        "abyss_talent": { // (4)
            "cur_talent": "number", // Current level.
            "max_talent": "number" // Maximum level.
        },
        "refresh_time": "number", // Time indicating next reset (likely in seconds).
        "abyss_collect": [ // (3)
            {
                "type": "number", // identifier collection category.
                "cur_collect": "number", // Current collected items in category.
                "max_collect": "number" // Maximum collectible items in category.
            }
        ],
        "abyss_nest": {
            "is_nest": "boolean", // abyss nest is active (2).
            "is_hard_nest": "boolean" // abyss nest is in hard mode.
        },
        "abyss_throne": {
            "is_throne": "boolean", // abyss throne is active (1).
            "max_damage": "string" // Maximum damage achieved in the throne
        },
        "unlock": "boolean" // Withered Domain is unlocked.
    }
}
```
1. ![image](https://github.com/user-attachments/assets/2c62ed25-7de7-43ab-8162-538641b0694e)
2. ![image](https://github.com/user-attachments/assets/19289547-3597-49a1-b7cc-a37ec4b1f7ba)
3. ![image](https://github.com/user-attachments/assets/8eb774a8-ea0e-44e6-8e7a-5fc58f1bdb27)
4. ![image](https://github.com/user-attachments/assets/a47644f2-1a67-44d2-a15d-349e5fe17160)

## Lost void (https://sg-public-api.hoyolab.com/event/game_record_zzz/api/zzz/abysss2_abstract?uid=&region=)
```json
{
    "retcode": "number",
    "message": "string",
    "data": {
        "abyss_level": {
            "cur_level": "number", // Current level.
            "max_level": "number", // Maximum level.
            "icon": "string" // URL icon.
        },
        "abyss_task": { // Exploration Log
            "cur_task": "number", // Completed tasks.
            "max_task": "number" // Tasks available.
        },
        "abyss_duty": { // Bounty Commission Progress
            "cur_duty": "number", // Current number.
            "max_duty": "number" // Maximum number.
        },
        "refresh_time": "number", // Time remaining until the next refresh (likely in seconds).
        "abyss_max": {
            "max_name": "string", // Name of the Highest Difficulty Cleared completed. I think maximum difficult - 5.
            "heat_count": "number", // Current number of attempts or completions for the challenge, I think.
            "max_count": "number", // Total Clears on the Highest Difficulty Completed.
            "best_time": "number", // Best completion time for the challenge (likely in seconds).
            "has_data": "boolean" // Is data available.
        },
        "abyss_collect": [ // (1)
            {
                "type": "number", // Identifier collection category.
                "cur_collect": "number", // Current collected items in the category.
                "max_collect": "number" // Maximum collectible items in the category.
            }
        ],
        "unlock": "boolean" // Lost void is unlocked.
    }
}
```
1. ![image](https://github.com/user-attachments/assets/fc479de6-cbaa-4dd4-86ba-147037cd8ed9)

## Deadly Assault (https://sg-public-api.hoyolab.com/event/game_record_zzz/api/zzz/mem_detail?uid=&region=&schedule_type=(1|2))
```json
{
    "retcode": "number",
    "message": "string",
    "data": {
        "start_time": "string", // timestamp start date
        "end_time": "string", // timestamp end date
        "rank_percent": "number", // idk
        "list": [], // idk
        "has_data": "boolean",
        "nick_name": "string",
        "avatar_icon": "string",
        "total_score":  "number",
        "total_star":  "number",
        "zone_id":  "number"
    }
}
```


**number in bracket - number screenshot**

**Comment by sanioooook** [comment]
## Updates for Deadly Assault
```json
{
    "retcode": "number",
    "message": "string",
    "data": {
        "start_time": {
            "year": "number",
            "month": "number",
            "day": "number",
            "hour": "number",
            "minute": "number",
            "second": "number"
        },
        "end_time": {
            "year": "number",
            "month": "number",
            "day": "number",
            "hour": "number",
            "minute": "number",
            "second": "number"
        },
        "rank_percent": "number", // I think it's 1
        "list": [], // idk
        "has_data": "boolean",
        "nick_name": "string", // nickname in game
        "avatar_icon": "string", // url to avatar in game (no hoyolab)
        "total_score": "number", // 2. sum of all points in current season
        "total_star": "number", // 3. sum of all stars in current season
        "zone_id": "number"
    }
}
```
![image](https://github.com/user-attachments/assets/9c585107-db06-415c-ad8b-40bc7faf5f06)

**Comment by seriaati** [comment]
@sanioooook 
Deadly assault and lost void were added in the latest git version, you can try them out beforehand if you want.

**Comment by sanioooook** [comment]
I've already tried it. everything works great, thanks
