### ISSUE TITLE
Hoyolab check in?

### ISSUE THREAD

**Issue by rushkii** [seriaati/genshin.py#26]
Does Hoyoverse remove the Hoyolab check in API? I still use `genshinstats` but when I use Hoyolab check in it throw an error `genshinstats.errors.GenshinStatsException: Internal database error, see original message`, did they remove it now?

**Comment by ashleney** [comment]
May I see the original message? (`error.original` / `repr(error)`)

I am unable to test this for myself because I have already claimed the daily reward.

**Comment by rushkii** [comment]
> May I see the original message? (`error.original` / `repr(error)`)
> 
> I am unable to test this for myself because I have already claimed the daily reward.

The error says `HoYoLAB is currently carrying out server migration. This function is not available at the moment~` [screenshot](https://i.ibb.co/fn3GWyZ/image.png)
Only Hoyolab check in, game daily rewards doesn't

**Comment by ashleney** [comment]
Daily check-in seems to be working just fine for me. Maybe the migration has already finished?

**Comment by rushkii** [comment]
> Daily check-in seems to be working just fine for me. Maybe the migration has already finished?

It's not finished yet, see `hoyolab_check_in()` function from [genshinstats library](https://github.com/thesadru/genshinstats/blob/ea24490184408829f175cb0a8f0e2bc97a55f6c4/genshinstats/hoyolab.py#L61) this function doesn't work, I'm not using `genshin.py` yet

**Comment by ashleney** [comment]
Oh, that one. I thought I got rid of that one completely, I'm surprised the function still exists.

Are you asking me to look into and potentially fix the genshinstats function or to implement it in genshin.py?

**Comment by rushkii** [comment]
> Oh, that one. I thought I got rid of that one completely, I'm surprised the function still exists.
> 
> Are you asking me to look into and potentially fix the genshinstats function or to implement it in genshin.py?

Just implement it in genshin.py I think, but that API still not work 🤔 just keep update about that API and implement it in genshin.py will be a pleasure.
