### ISSUE TITLE
Can't set authkey on GenshinClient due to size mismatch

### ISSUE THREAD

**Issue by Ennea** [seriaati/genshin.py#3]
Trying to create a new `GenshinClient` instance with an `authkey` fails with the error `authkey must have precisely 1024 characters`. Trying to set the `authkey` on an existing instance results in the same error. The auth key I'm providing is longer than 1024 characters. The base64 decoded auth key, however, is exactly 1024 characters long. Providing that instead of the base64 encoded one results in a different error: `authkey is not a valid base64 encoded string`

**Comment by ashleney** [comment]
The validation always works for me. May I see the full traceback of `authkey is not a valid base64 encoded string`?

I think automatically decoding the authkey might be a good idea but you shouldn't need to interact with the encoded authkey in the first place - `genshin.extract_authkey` should take care of that.

May I see the authkey you're using?

**Comment by Ennea** [comment]
I was using `extract_authkey`, but it just returns the same base64 encoded string that's in the URL. Is it supposed to also decode it? Anyway, here's the stack trace for both scenarios. Passing the base64 encoded auth key:
<pre lang="py">>>> client = genshin.GenshinClient(authkey=authkey)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\user\playground\.venv\lib\site-packages\genshin\client.py", line 101, in __init__
    self.authkey = authkey
  File "C:\Users\user\playground\.venv\lib\site-packages\genshin\client.py", line 168, in authkey
    raise ValueError("authkey must have precisely 1024 characters")
ValueError: authkey must have precisely 1024 characters</pre>

Passing the decoded auth key:
<pre lang="py">>>> client = genshin.GenshinClient(authkey=base64.b64decode(authkey))
Traceback (most recent call last):
  File "C:\Users\user\playground\.venv\lib\site-packages\genshin\client.py", line 163, in authkey
    base64.b64decode(authkey, validate=True)
  File "C:\Users\user\Tools\Python\Python39-32\lib\base64.py", line 86, in b64decode
    raise binascii.Error('Non-base64 digit found')
binascii.Error: Non-base64 digit found

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\user\playground\.venv\lib\site-packages\genshin\client.py", line 101, in __init__
    self.authkey = authkey
  File "C:\Users\user\playground\.venv\lib\site-packages\genshin\client.py", line 165, in authkey
    raise ValueError("authkey is not a valid base64 encoded string") from e
ValueError: authkey is not a valid base64 encoded string</pre>

**Comment by ashleney** [comment]
In case you were to comment out the validation and try to request an endpoint would it still work? If yes then I might need to edit the validation.

**Comment by Ennea** [comment]
Sending a request to miHoYo's endpoint manually works with the auth key I have. Haven't tried modifying your code, however.

**Comment by Ennea** [comment]
Taking a look at the code, however, I see why it wouldn't work :) Line 163 in `client.py` is:
<pre lang="py">base64.b64decode(authkey, validate=True)</pre>

You're not assigning the return value to anything, and then check the length of the original, base64 encoded auth key in line 167.

**Comment by ashleney** [comment]
No that is intended. This is just for validation so you the user can tell the authkey is invalid even before requesting anything.

**Comment by Ennea** [comment]
But the length of the base64 encoded auth key obviously cannot be 1024 if the decoded auth key is 1024 characters long.

**Comment by ashleney** [comment]
May I see the authkey? You can just swap cases in some characters or smth if you don't want others to see your wish & transaction histories.

**Comment by ashleney** [comment]
> But the length of the base64 encoded auth key obviously cannot be 1024 if the decoded auth key is 1024 characters long.

The decoded authkey is not used at any point. That line is only for validation.

It checks whether the authkey is actually a base64 string but it doesn't care what the actual decoded value is. Then it checks if the same encoded base64 string is also 1024 characters long.

**Comment by Ennea** [comment]
> 
> 
> May I see the authkey? You can just swap cases in some characters or smth if you don't want others to see your wish & transaction histories.

Sure:
```
TG9yZW0gaXBzdW0gZG9sb3Igc2l0IGFtZXQsIGNvbnNlY3RldHVyIGFkaXBpc2NpbmcgZWxpdC4gUHJhZXNlbnQgaWFjdWxpcywgcXVhbSBzaXQgYW1ldCBzb2xsaWNpdHVkaW4gbHVjdHVzLCBleCBsZWN0dXMgdGVtcHVzIG51bGxhLCBxdWlzIGZlcm1lbnR1bSBhbnRlIHVybmEgYXQgcHVydXMuIENsYXNzIGFwdGVudCB0YWNpdGkgc29jaW9zcXUgYWQgbGl0b3JhIHRvcnF1ZW50IHBlciBjb251YmlhIG5vc3RyYSwgcGVyIGluY2VwdG9zIGhpbWVuYWVvcy4gTWFlY2VuYXMgZmVybWVudHVtIG1pIG5vbiBkdWkgZGFwaWJ1cyBwbGFjZXJhdC4gQWVuZWFuIGxpYmVybyBtZXR1cywgdmVzdGlidWx1bSB1dCB0b3J0b3IgbmVjLCBibGFuZGl0IHBlbGxlbnRlc3F1ZSBtYWduYS4gRnVzY2UgbmVxdWUgbmliaCwgZmFjaWxpc2lzIGFjIGV4IHNlZCwgc29kYWxlcyBzZW1wZXIgdHVycGlzLiBMb3JlbSBpcHN1bSBkb2xvciBzaXQgYW1ldCwgY29uc2VjdGV0dXIgYWRpcGlzY2luZyBlbGl0LiBQcmFlc2VudCBpYWN1bGlzLCBxdWFtIHNpdCBhbWV0IHNvbGxpY2l0dWRpbiBsdWN0dXMsIGV4IGxlY3R1cyB0ZW1wdXMgbnVsbGEsIHF1aXMgZmVybWVudHVtIGFudGUgdXJuYSBhdCBwdXJ1cy4gQ2xhc3MgYXB0ZW50IHRhY2l0aSBzb2Npb3NxdSBhZCBsaXRvcmEgdG9ycXVlbnQgcGVyIGNvbnViaWEgbm9zdHJhLCBwZXIgaW5jZXB0b3MgaGltZW5hZW9zLiBNYWVjZW5hcyBmZXJtZW50dW0gbWkgbm9uIGR1aSBkYXBpYnVzIHBsYWNlcmF0LiBBZW5lYW4gbGliZXJvIG1ldHVzLCB2ZXN0aWJ1bHVtIHV0IHRvcnRvciBuZWMsIGJsYW5kaXQgcGVsbGVudGVzcXVlIG1hZ25hLiBGdXNjZSBuZXF1ZSBuaWJoLCBmYWNpbGlzaXMgYWMgZXggc2VkLCBzb2RhbGVzIHNlbXBlciB0dXJwaXMuIExvcmVtIGlwc3VtIGRvbG9yIHNpdCBhbWV0LCBjb25zZWN0ZXR1ciBhZGlwaXNjaW5nIGVsaXQuIFByYWVzZW50IGlhY3VsaXMsIHF1YW0gc2l0IGFtZXQgc29sbGljaXR1ZGluIGx1Y3R1cywgZXggbGVjdHVzIHRlbXB1cyBudWxsYQ==
```

**Comment by ashleney** [comment]
After a bit of investigation, it seems there's truly no rule about authkeys being 1024 characters. They may also be 1368 characters instead. Both you and one of my friends have 1368. I'll remove the length check then.
