### ISSUE TITLE
Enable real-time notes automatically 

### ISSUE THREAD

**Issue by ahmadkeren** [seriaati/genshin.py#32]

**Comment by GauravM512** [comment]
You need to manually enable the real time option from your battle chronicle.

**Comment by ashleney** [comment]
Great idea honestly. I'll see what I can do about it.

**Comment by GauravM512** [comment]
> Great idea honestly. I'll see what I can do about it.

Wut? It is possible?

**Comment by ashleney** [comment]
Yes, anything you can do on the website is also possible through the API.

**Comment by ahmadkeren** [comment]
Thanks... UwU..
