### ISSUE TITLE
Code Redemption Broken

### ISSUE THREAD

**Issue by EffortlessFury** [seriaati/genshin.py#35]
I'm getting this error when trying to redeem a code.
`genshin.errors.GenshinException: [-502] fail to get RPC client`

Seems that the CODE_URL has changed, and replacing it with `https://sg-hk4e-api.hoyoverse.com/common/apicdkey/api/webExchangeCdkey` fixes the issue.

**Comment by re1von** [comment]
I get a similar output using version 1.2.1 when I try to activate the redeem code:
```python
genshin.errors.GenshinException: Recieved a response with an invalid content type:
404 page not found
```
I manually downloaded the latest version files from pypi and saw:
```python
CODE_URL = Route("https://hk4e-api-os.mihoyo.com/common/apicdkey/api/webExchangeCdkey")
```
If I replace the url with `https://sg-hk4e-api.hoyoverse.com/common/apicdkey/api/webExchangeCdkey `, then this function works fine.
Why hasn't it been fixed yet?

**Comment by ashleney** [comment]
No release has been made since then. Meanwhile you'll have to download directly from git rather than pypi.
