### ISSUE TITLE
Genshin Characters Data problem

### ISSUE THREAD

**Issue by yaser01** [seriaati/genshin.py#37]
Thanks for the awesome work
After the last update [My old version was 0.4.0]
Some characters give icon URL not found like "Yae Miko" : https://upload-os-bbs.mihoyo.com/game_record/genshin/character_icon/UI_AvatarIcon_YaeMiko.png
also the "Traveler" has no element [previously it has its current element like Anemo or Geo ...]
Is there any problem ?

**Comment by ashleney** [comment]
Seems like Yae's icon was moved. The traveler element is indeed a bug.
