### ISSUE TITLE
Game record endpoint update with in-game profile info

### ISSUE THREAD

**Issue by rushkii** [seriaati/genshin.py#40]
Hoyo seems like updated the game record endpoint with in-game profile info such as nickname, AR, and server name. Are you have implemented this?

URL: https://bbs-api-os.hoyolab.com/game_record/genshin/api/index?server={SERVER_NAME}&role_id={UID}

**Comment by nano-shino** [comment]
It's always been there:
```
gs.get_record_cards(...)
GenshinRecordCard(game_biz='', uid=..., level=60, nickname='nanoshino', server='os_usa', server_name='America Server',...)
```

**Comment by rushkii** [comment]
> It's always been there:
> 
> ```
> gs.get_record_cards(...)
> GenshinRecordCard(game_biz='', uid=..., level=60, nickname='nanoshino', server='os_usa', server_name='America Server',...)
> ```

You don't read the URL properly, aren't you? It's not record cards, `get_record_cards` is fetching using hoyolab **UID**, but the `get_genshin_user` uses in-game UID **[see this](https://user-images.githubusercontent.com/47179236/173541034-b8c548e2-8241-443b-9fc2-db0ae783a231.png)**

**Comment by nano-shino** [comment]
Now I see what you meant. It should be just an update of GenshinUserStats pydantic model to include the new fields.

**Comment by rushkii** [comment]
> Now I see what you meant. It should be just an update of GenshinUserStats pydantic model to include the new fields.

Yess, that's what I meant
