### ISSUE TITLE
pydantic.error_wrappers.ValidationError: 21 validation errors for Activities

### ISSUE THREAD

**Issue by TIMMLOPK** [seriaati/genshin.py#45]
I got this error when using `get_full_genshin_user`.However `get_genshin_characters` works without error.I try to fetch hoyolab api, it response as normal.This error seem appear at a part of user.Anyone know why ?
```
pydantic.error_wrappers.ValidationError: 21 validation errors for Activities
hyakunin_ikki_v25 -> records -> 0 -> battles -> 0 -> characters -> 1 -> __root__
  Character data incomplete (type=value_error)
```

**Comment by ashleney** [comment]
I had no luck reproducing this error. Hopefully, this will be consistently fixed with the new upcoming model library.
