### ISSUE TITLE
[Question] How to return a dict model?

### ISSUE THREAD

**Issue by rushkii** [seriaati/genshin.py#47]
Hello, I want to use `get_genshin_user` but printed in dict model, not a class model. Is it possible to return a dict model?

**Comment by ashleney** [comment]
```py
user = await client.get_genshin_user(uid)
return user.dict()
```

**Comment by rushkii** [comment]
> ```python
> user = await client.get_genshin_user(uid)
> return user.dict()
> ```

Thanks, that helps.
