### ISSUE TITLE
[invalid]Cannot recognize servers with UID starting with 4

### ISSUE THREAD

**Issue by luoshuijs** [seriaati/genshin.py#49]
There are already players with UIDs starting with 4 on the Chinese genshin server.
The `recognize_genshin_server` function needs to be modified

https://github.com/thesadru/genshin.py/blob/ee6cdb5776252718844dcc7e7a4881b1cbf5acfe/genshin/utility/uid.py#L32-L47

**Comment by luoshuijs** [comment]
~~But I'm very sorry that I don't know the server that this UID corresponds to at the moment, **I only know that it is real**. >_<~~
Just checked, it seems that the UID error is caused by an unexpected program error, not a genshin module problem, I'm sorry, I will close this issue

**Comment by luoshuijs** [comment]
Just checked, it seems that the UID error is caused by an unexpected program error, not a genshin module problem, I'm sorry, I will close this issue

**Comment by luoshuijs** [comment]
The reason for this is that I have a strange user who is bound to the Honkai account only. My program didn't check the content returned by `get_record_card`, which led to the wrong use of Honkai's UID. hahahaha.

**Comment by ashleney** [comment]
Aren't `ChineseClient` and `get_record_card` those deprecated anyways?

**Comment by luoshuijs** [comment]
Thank you very much for the reminder. My early project was based on version 0.4.0 and at that time I checked the documentation and the client integration was still on the to-do list. Until now I have been using `ChineseClient` and `GenshinClient`. I will apply the new client to my project when I have time.>_<
