### ISSUE TITLE
TypeError: 'MergedPaginator' object is not iterable

### ISSUE THREAD

**Issue by QueenLaurie** [seriaati/genshin.py#52]
i want to try wish history but i got this error
`TypeError: 'MergedPaginator' object is not iterable`

this is my code
```python
import asyncio
import genshin
cookies = {"ltuid": xxxxxxxx, "ltoken": "xxxxxxxxxxxxxx"}
client = genshin.Client(cookies)

async def main():
    for wish in client.wish_history():
        print(f"{wish.time} - {wish.name} ({wish.rarity}* {wish.type})")

asyncio.run(main())
```

if my coding is wrong I'm sorry, I'm just learning to use python

**Comment by ashleney** [comment]
It's an async iterator. You're supposed to use
```py
async for wish in client.wish_history():
    ...
```

**Comment by QueenLaurie** [comment]
ah thanks,but i got another error,it says authkeys,i already put the authkey in wish_history(authkey="") but still can't

**Comment by QueenLaurie** [comment]
where i cant get authkey? from wish history url?

**Comment by QueenLaurie** [comment]
oh this already works,thanks
