### ISSUE TITLE
genshin.error.InvalidCookies

### ISSUE THREAD

**Issue by AFOEK** [seriaati/genshin.py#57]
**How to reproduce ?**
Using CLI to login after that invoke `python -m genshin accounts --cookies "ltoken=...; ltuid=..."`

**Current behavior**
It's just display error which state:
```
genshin.errors.InvalidCookies: [-100] Cookies are not valid.
```

**Comment by ashleney** [comment]
That's just an issue on your part. Works fine for me.

Using the example cookies provided in README.md here:
```
~ $ python -m genshin genshin stats 710785423 --cookies "ltuid=119480035; ltoken=cnF7TiZqHAAvYqgCBoSPx5EjwezOh1ZHoqSHf7dT"
User stats of 710785423

Stats:
Achievements: 488
Days Active: 545
Characters: 34
Waypoints Unlocked: 190
Anemoculi: 66
Geoculi: 131
Electroculi: 181
Common Chests Opened: 1403
Exquisite Chests Opened: 1019
Precious Chests Opened: 296
Luxurious Chests Opened: 118
Remarkable Chests Opened: 44
Domains Unlocked: 35

Explorations:
The Chasm: Underground Mines - explored 100.0% | Lumenstone Adjuvant 10
The Chasm - explored 85.8% | Lumenstone Adjuvant 10
Enkanomiya - explored 91.1% |
Inazuma - explored 98.0% | Sacred Sakura's Favor 50, Reputation 10
Dragonspine - explored 100.0% | Frostbearing Tree 12
Liyue - explored 94.5% | Reputation 8
Mondstadt - explored 100.0% | Reputation 8
Sumeru - explored 0.0% | Tree of Dreams 0, Reputation 0

Teapot:
level 10 | comfort 21220 (Fit for a King)
Unlocked realms: Floating Abode, Emerald Peak, Cool Isle
```

**Comment by AFOEK** [comment]
Ahh, I think I missing some argument for the CLI. Before I close the issue I have little suggestion some part of documentation are vague. Thanks

**Comment by AFOEK** [comment]
> Ahh, I think I missing some argument for the CLI. Before I close the issue I have little suggestion some part of documentation are vague. Thanks

For addition, I already try it's seems my `ltuid` are more shorter than yours, I have 8 digits I think it failed due server differences (mine are ASIA server tho)

**Comment by ashleney** [comment]
8 digits just mean your hoyolab account was created early. It shouldn't actually matter at all. What matters is the UID which is always 9 digits.

All os servers are handled seamlessly, including asia. The only problem would be if you were using a mainland china account, in which case you'd need to specify that on client initialization.

**Comment by AFOEK** [comment]
Correct me if I'm wrong, I think my argument to the CLI is wrong.
`python -m genshin genshin stats <ingame_UID> --cookies "ltuid=<ltuid_cookie>; ltoken=<cookie_token>"`
