### ISSUE TITLE
Issue since Genshin 3.0

### ISSUE THREAD

**Issue by yabb85** [seriaati/genshin.py#60]
Hi,

Since the last version this script cannot found the authkey from output_log.txt
After check with patch https://github.com/thesadru/genshin.py/pull/59 the new error is:
genshin.errors.AuthkeyTimeout: [-101] Authkey has timed out.

I relaunch software and see wishes history but the result is the same.

in the file [genshin/utility/logfile.py](https://github.com/thesadru/genshin.py/pull/59/files#diff-94499ff2bb6aa1f1516d69769c2c3be1328597a023581cd5da57432209cace9d) 
replace lines
```python
match = re.search(r"https://.+?authkey=([^&#]+)&game_biz=hk4e_", string, re.MULTILINE)
if match is not None:
    return urllib.parse.unquote(match.group(1))
```
by
```python
list_authkey = re.findall(r"https://.+?authkey=([^&#]+)&game_biz=hk4e_", string)
if len(list_auth_key) > 0:
    return urllib.parse.unquote(list_authkey[-1])
```
works

best regards

**Comment by ashleney** [comment]
If they don't fix the workflows I'll probably just end up doing it myself tbh.

**Comment by yabb85** [comment]
After check it is ok wih last commit https://github.com/thesadru/genshin.py/commit/69c1a3abd38bc4951f50d46797e659489ff4ce81.
Thanks
