### ISSUE TITLE
genshin.errors.InvalidCookies: [-1071] Cookies are not valid.

### ISSUE THREAD

**Issue by Stawa** [seriaati/genshin.py#62]
I got this error from using the `redeem_code` function. 
The weird thing is, when I use other functions such as claim_daily_reward and genshin_accounts, it doesn't raise any errors.

```py
Client = genshin.Client(
    cookies={
          "ltuid": 1234,
          "ltoken": "xxxxx"
    },
    authkey="xxxx",
)

x = await Client.redeem_code(code="GENSHINGIFT", uid=await Client._get_uid(game=Game.GENSHIN)
print(x)
```

I am not sure if I redeemed the claimed code, but I'm not really sure what the problem with this code is.

**Comment by ashleney** [comment]
`redeem_code` is a fairly inconsistent method due to it not being part of the hoyolab API.
> For some endpoints like `redeem_code`, you need to set account_id and cookie_token cookies. You can get them by going to [genshin.mihoyo.com](https://genshin.mihoyo.com/en/gift).

```py
client = genshin.Client(
    cookies={
          "ltuid": 1234,
          "account_id": 1234, # identical to ltuid
          "ltoken": "xxxxx",
          "cookie_token": "xxxx", # unique token
    },
    authkey="xxxx",
)

# (this function does not return anything)
await client.redeem_code("GENSHINGIFT")
```

**Comment by Stawa** [comment]
I didn't know if it requires `cookie_token` and `account_id`. Thank You!
