### ISSUE TITLE
Request: Implement enka.network API

### ISSUE THREAD

**Issue by rushkii** [seriaati/genshin.py#63]
Can you implement enka.network API to this library? enka.network has a fetch in-game profile with a character set and profile signature.

**Comment by ashleney** [comment]
There already exist libraries that support enka. It's a very different API from the one mihoyo offers so it would probably just end up as a completely separate package anyways.

For now I recommend https://github.com/mrwan200/EnkaNetwork.py

**Comment by rushkii** [comment]
> There already exist libraries that support enka. It's a very different API from the one mihoyo offers so it would probably just end up as a completely separate package anyways.
> 
> For now I recommend https://github.com/mrwan200/EnkaNetwork.py

Oh, I thought you want to implement it to your library. Thanks anyway.
