### ISSUE TITLE
Request: Implement login by UID

### ISSUE THREAD

**Issue by rushkii** [seriaati/genshin.py#64]
Can you implement the login by UID? I think its the same as login_by_password with geetest. You can see:
- https://sg-public-api.hoyoverse.com/common/aigis/api/preCheck 
- https://sg-public-api.hoyoverse.com/common/badge/v1/login/sendCode

there are important payload and headers for sendCode endpoint:
**Payload**
```
{"game_biz":"hk4e_global","lang":"en-us","level":"YOUR_AR","region":"YOUR_SERVER","uid":"YOUR_UID"}
```
**Headers**
```
x-rpc-aigis: 4ffcb4090c444aa0bee4c64d4616a704;eyJnZWV0ZXN0X2NoYWxsZW5nZSI6IjEwY2Y2OWNlMzlhMzljZTZkZmI5ZTk0MDE2YjQxODYwIiwiZ2VldGVzdF92YWxpZGF0ZSI6ImE3MjdmOWU4ZGQzZWU3ZDJiMWFjNDg1NjczMDU4ZWJiIiwiZ2VldGVzdF9zZWNjb2RlIjoiYTcyN2Y5ZThkZDNlZTdkMmIxYWM0ODU2NzMwNThlYmJ8am9yZGFuIn0=
x-rpc-app_id: ap0u1hssh534
```

Or you want to analyze or reverse engineering it just go to the new event at https://act.hoyoverse.com/ys/event/e20220928review_data/index.html?mhy_presentation_style=fullscreen&mhy_auth_required=true&game_biz=hk4e_global&mhy_landscape=true
HoYo is now accepting the login by UID with the verification code.

**Comment by ashleney** [comment]
This has been implemented by hoyo a few times already but every time they only gave a cookie for web events, not for the hoyolab API. If this time it gives all the cookies it might be very helpful.

**Comment by ashleney** [comment]
Unfortunately the only returned cookie is `e_hk4e_token`
