### ISSUE TITLE
Offerings contain mixed types of `dict` and `Offering` (Model)

### ISSUE THREAD

**Issue by luoshuijs** [seriaati/genshin.py#67]
One of the recent updates to `class Offering(APIModel)` has resulted in `get_genshin_user()`'s return value, `GenshinUserStats.explorations[x].offerings`, became a list that contains two mixed types: `Offering` (Model) and `dict`.

Specifically, the `Tree of Dreams` (or `梦之树` on CN server) is having a type of `dict`.

We see that `offerings` has changed from `typing.Sequence[Offering]` to `typing.Sequence[typing.Any]`:

https://github.com/thesadru/genshin.py/blob/99a6a41277ddd68edb1c5b7ff2cd3606d2249d37/genshin/models/genshin/chronicle/stats.py#L88

and is now mixing `Offering` and `dict`:

https://github.com/thesadru/genshin.py/blob/99a6a41277ddd68edb1c5b7ff2cd3606d2249d37/genshin/models/genshin/chronicle/stats.py#L92

This change was causing some issues to us downstream users - we are expecting to use the offering model consistently in the iterable.

Is this the expected behavior? If so, do you mind sharing why the change was made?

**Comment by ashleney** [comment]
This is an issue of simply making the validator use `pre=True`. Should be fixed soon.
