### ISSUE TITLE
"'MultiCookieClient' object has no attribute 'get_calculator_characters'"

### ISSUE THREAD

**Issue by ahmadkeren** [seriaati/genshin.py#7]
Excuse me, i try another method like "get_users, get_spiral_abyss, get_diary, etc" anything is work as well..
But when i try calculator method, why the result is always "'MultiCookieClient' object has no attribute 'get_calculator_characters'"?
Thanks..

**Comment by ahmadkeren** [comment]
![Screen Shot 2021-12-24 at 17 43 07](https://user-images.githubusercontent.com/49072140/147345996-ec3de017-b085-48c9-ba46-43dea44e5c7e.png)

**Comment by ashleney** [comment]
The latest changes have not yet been published to pypi due to some conflicts with the upcoming honkai client (see #6).

If you want to use these new features you should install the library directly from git:
```
pip uninstall genshin
pip install git+https://github.com/thesadru/genshin.py
```

**Comment by ahmadkeren** [comment]
> git+https://github.com/thesadru/genshin.py

Thanks ^_^
