### ISSUE TITLE
Check if HoYoLAB account is verified with LTUID

### ISSUE THREAD

**Issue by TofuBoy05** [seriaati/genshin.py#72]
Hello, I want to know if it is possible to check if an account is verified with only LTUID.
![Screenshot_20221020-133428.jpg](https://user-images.githubusercontent.com/98312802/196864505-7c481638-f29b-4d45-842c-7dc8b60f4478.jpg)

**Comment by ashleney** [comment]
Try
```py
user = await client.get_hoyolab_user(hoyolab_id)
print(user.certification)
```

If `user.certification.type == 2` it should be an artist.
