### ISSUE TITLE
genshin[cookies,rsa] does not exist

### ISSUE THREAD

**Issue by littledot** [seriaati/genshin.py#75]
https://thesadru.github.io/genshin.py/authentication/ talks about using `pip install genshin[cookies,rsa]` to refresh cookies. But these packages do not exist. I've tried `genshincookies genshin-cookies genshinrsa genshin-rsa` all failed.

What's the correct id for the package?

**Comment by ashleney** [comment]
Weird, maybe an issue with escaping? It's supposed to be a shorthand for `pip install "genshin[cookies]" "genshin[rsa]"` which in itself is a shorthand for `pip install genshin browser-cookie3 rsa`

**Comment by littledot** [comment]
You're right I'm using zsh and brackets have special meaning. Escaped the brackets and got it working.
