### ISSUE TITLE
Will there be support for teapot replication ID's? 

### ISSUE THREAD

**Issue by ChrisMGeo** [seriaati/genshin.py#82]
Title.
I'm wondering if there's a way to validate teapot replica ID's and their creator's UID.

**Comment by ashleney** [comment]
Genshin.py uses the hoyolab app API. Unless there is a way to preview one from the app or website I doubt it is possible. 
There are other projects that focus on getting public in-game data such as enka. Not a high chance they will bother with anything like this but it's still more likely than here.
