### ISSUE TITLE
Use something better than pydantic

### ISSUE THREAD

**Issue by ashleney** [seriaati/genshin.py#85]
Pydantic is great and all but it's incredibly limiting for validation. (see the [custom model](https://github.com/thesadru/genshin.py/blob/master/genshin/models/model.py) that has to be used).

This should either be decoupled into a separate library or at least cleaned up. 
Considering dropping re-serialization for optimization.

**Comment by ashleney** [comment]
Actually, it turns out that pydantic has recently started work on finally integrating pydantic-core into the library after months of it only being instantiable with a schema. Might turn out that we don't really need a new library (I hope)

https://github.com/pydantic/pydantic/commit/594effa279668bd955e98f1cd5c036b37d3bbd40

**Comment by seriaati** [comment]
Are we still planning to use something better than pydantic?

**Comment by ashleney** [comment]
A lot of tech debt was accumulated since then, so unless someone wants to do a full rewrite I think we'll be sticking with pydantic (v2) long into the future.

**Comment by seriaati** [comment]
Should we close this issue as not completed then?

**Comment by FichteFoll** [comment]
Just out of curiousity, what other options besides pydantic would be considered viable?

**Comment by ashleney** [comment]
They are viable but the project heavily relies on pydantic internals so a huge rewrite would be needed.
