### ISSUE TITLE
get_browser_cookies() code misspell

### ISSUE THREAD

**Issue by Ftalysh** [seriaati/genshin.py#88]
Seems like there is a misspell in genshin/utility/fs.py as far as python call `client.set_browser_cookies()` returns an error: 

> ---> 23     import browser_cookie3  # pyright: ignore
> "ModuleNotFoundError: No module named 'browser_cookie3'"

Probably you meant "import browser_cookies"

**Comment by ashleney** [comment]
It's an optional dependency https://github.com/borisbabic/browser_cookie3
