### ISSUE TITLE
Support v2 cookies

### ISSUE THREAD

**Issue by luoshuijs** [seriaati/genshin.py#89]
The ch server fully uses the v2 version of the cookies
```
ltoken_v2=xxxx
ltmid_v2=xxx
cookie_token_v2=xxxx
account_mid_v2=xxxxx
```
It is not possible to get the user id from `account_mid_v2` because it is a random string character generated by the ch server.
https://github.com/thesadru/genshin.py/blob/dbebc29f485f01e352e75c6e389e754369101a9c/genshin/client/manager/managers.py#L238-L248

**Comment by luoshuijs** [comment]
when I use v2 cookies, I can't get hoyolab_uid, which can lead to other problems, such as caching and other requests that depend on hoyolab_uid.
https://github.com/thesadru/genshin.py/blob/dbebc29f485f01e352e75c6e389e754369101a9c/genshin/client/components/base.py#L395

**Comment by GauravM512** [comment]
How do you get V2 cookie in the first place?

**Comment by luoshuijs** [comment]
> How do you get V2 cookie in the first place?

for now, only some users on the CN server are using the v2 cookies. but the new login sessions all use the v2 cookie.

**Comment by GauravM512** [comment]
> > How do you get V2 cookie in the first place?
> 
> for now, only some users on the CN server are using the v2 cookies. but the new login sessions all use the v2 cookie.

Thanks for clarifying 😊

**Comment by ashleney** [comment]
A fix has been pushed to the master branch. Hoyolab IDs are now not explicitly required but can be provided with `client.hoyolab_id = ...` or `Client(hoyolab_id=...)`

Tell me if it works for you.

**Comment by luoshuijs** [comment]
The fix does indeed work. Thank you for looking into it.

This may be a seperate request, but can you add this API for retrieving user's uid based on cookies?

`https://bbs-api.mihoyo.com/user/wapi/getUserFullInfo`

We don't have other methods of obtaining the user's uid given their cookies

**Comment by BachelorForever** [comment]
#90 Kinda fixed.

BTW I think the DS_SALT should be updated, since we are using 2.11.1

But the newest is 2.40.0 (from x-rpc-app_version header)

Also, the newest header is ```Ds``` not ```ds```, but ```ds``` also works.

**Comment by ashleney** [comment]
http headers are case insensitive

**Comment by BachelorForever** [comment]
Oh good to learn something new everyday.

But still a difference between official requests and our requests tho.

**Comment by ashleney** [comment]
I hope hoyo doesn't use a framework that makes a distinction like that.
